import {
    PencilSquareIcon,
    TrashIcon,
    PlusIcon,
    Bars3Icon,
    HomeIcon,
    Squares2X2Icon,
    MagnifyingGlassIcon,
    XMarkIcon,
    MoonIcon,
    SunIcon,
    ListBulletIcon,
    BellIcon,
    CheckCircleIcon,
    ExclamationCircleIcon,
    XCircleIcon,
    CheckIcon,
    ArrowUpOnSquareIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    FunnelIcon,
    CubeIcon,
    ClipboardDocumentCheckIcon,
    EllipsisVerticalIcon,
    MinusIcon,
    UserIcon,
    EllipsisHorizontalIcon,
    ShoppingCartIcon,
    PlusCircleIcon,
    MinusCircleIcon
} from '@heroicons/vue/24/outline'

import { InformationCircleIcon } from '@heroicons/vue/24/solid'

export default function useHeroicons() {
    return {
        PencilSquareIcon,
        TrashIcon,
        PlusIcon,
        Bars3Icon,
        HomeIcon,
        Squares2X2Icon,
        MagnifyingGlassIcon,
        XMarkIcon,
        MoonIcon,
        SunIcon,
        InformationCircleIcon,
        CheckCircleIcon,
        XCircleIcon,
        ExclamationCircleIcon,
        ListBulletIcon,
        BellIcon,
        CheckIcon,
        ArrowUpOnSquareIcon,
        ChevronLeftIcon,
        ChevronRightIcon,
        FunnelIcon,
        CubeIcon,
        ClipboardDocumentCheckIcon,
        EllipsisVerticalIcon,
        MinusIcon,
        UserIcon,
        EllipsisHorizontalIcon,
        ShoppingCartIcon,
        PlusCircleIcon,
        MinusCircleIcon
    }
}
